deployment:
  tasks:
    - export DEPLOYPATH=/home/bnqxhxxz90u5/public_html/
    - /bin/cp scripts.js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
